---
# Setup /etc/hosts
- name: Setup /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^{{ hostvars[item].node_ip }}' line='{{ hostvars[item].node_ip }}	{{ hostvars[item].node_name }}'
  with_items: convergeio_nodes
  sudo: true

# Setup hostname
- name: Setup hostname
  hostname: name='{{ node_name }}'
  sudo: true

# Setup isci
- name: Setup iscsi name
  lineinfile: dest=/etc/iscsi/initiatorname.iscsi regexp='^InitiatorName' line='InitiatorName=iqn.1993-08.org.debian:01:{{ node_name }}'
  sudo: true

# Reboot Server
- name: Reboot server
  command: /sbin/shutdown -r now
  sudo: true
  tags:
    - restart

- name: Checking SSH connectivity
  local_action: wait_for host={{ inventory_hostname }} port=22 timeout=300 state=started
  tags:
    - restart

# Debug
- name: Debug
  lineinfile: dest=/etc/iscsi/initiatorname.iscsi regexp='^InitiatorName' line='InitiatorName=iqn.1993-08.org.debian:01:{{ node_name }}'
  sudo: true
  run_once: true
  delegate_to: "{{ convergeio_master_node }}"

# Setup ConvergeIO
- name: Setup config for ConvergeIO
  template: src=aws.cfg.j2 dest=/etc/convergeio/config/aws.cfg 
  sudo: true
  run_once: true
  delegate_to: "{{ convergeio_master_node }}"
  tags:
    - setup

# Init ConvergeIO
- name: Init ConvergeIO
  shell: nohup cioadm dminit aws.cfg > /root/cioadm_output.log 2>&1 & wait
  sudo: true
  run_once: true
  delegate_to: "{{ convergeio_master_node }}"
  tags:
    - init

- name: Create vdisks
  include: create_vdisks.yml tags=create_vdisks

  
