---
# Provision instances brought up
- name: Setup system on instances
  hosts: launched
  gather_facts: true
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - "{{ site_vars_path }}/system_users.yml"
        - vars/default/system_users.yml
  roles:
    - role: system_user
      system_users: "{{ users }}"
      sudo: true
    # The role would have also skipped users without awscli defined, just showing another way to filter
    - role: awscli
      awscli_users: "{{ users | selectattr('awscli', 'defined') | list }}"
